In [2]:
my_str = "ramesh ram"
print(my_str[1])
print("a"in my_str)
print("h" in my_str)
print(my_str[5])

a
True
True
h


In [2]:
import numpy as np


In [12]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.size)
print(arr1.shape)

[1 2 3 4 5]
5
(5,)


In [16]:
arr1 = np.arange(6)
print(arr1)

[0 1 2 3 4 5]


In [13]:
arr_zeros = np.zeros((3,4))
arr_ones = np.ones((3,4))
print(arr_zeros)
print(arr_ones)


print(arr_ones.size)
print(arr_ones.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
12
(3, 4)


In [15]:
arr3 = np.array([1,2])
arr4 = np.array([1,2])
print(arr3 + arr4)

[2 4]


In [16]:
arr3 = np.array([1,2])
arr4 = np.array([1,2])
print(arr3 * arr4)


[1 4]


In [17]:
arr5 = np.array([[1,2],
                 [4,6]])
print(arr5[1])
print(arr5[:,1])


[4 6]
[2 6]


In [21]:
arr5 = np.array([[1,2],
                 [4,6]])
arr6 = np.array([[3,5],
                [5,6]])
print(arr5 + arr6)


[[ 4  7]
 [ 9 12]]


In [22]:
arr5 = np.array([[1,2],
                 [4,6]])
arr6 = np.array([[3,5],
                [5,6]])
print(arr5 * arr6)


[[ 3 10]
 [20 36]]


In [23]:
arr5 = np.array([[1,2],
                 [4,6]])
arr6 = np.array([[3,5],
                [5,6]])
print(arr5 / arr6)


[[0.33333333 0.4       ]
 [0.8        1.        ]]


In [24]:
arr5 = np.array([[1,2],
                 [4,6]])
arr6 = np.array([[3,5],
                [5,6]])
print(arr5 - arr6)


[[-2 -3]
 [-1  0]]


In [31]:
a = np.array([1,2,3,4], dtype='int64')
print(a)
print(a.dtype)

[1 2 3 4]
int64


In [32]:
arr_zeros = np.zeros((3,4))
arr_ones = np.ones((3,4))
print(arr_zeros)
print(arr_ones)


print(arr_ones.size)
print(arr_ones.shape)
print(arr_ones.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
12
(3, 4)
float64
