<a href="https://colab.research.google.com/github/Gtramesh/DAY-2-FDP/blob/main/day_2_numpy_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_str = "ramesh ram"
print(my_str[1])
print("a"in my_str)
print("h" in my_str)
print(my_str[5])

a
True
True
h


In [ ]:
import numpy as np


In [ ]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.size)
print(arr1.shape)

[1 2 3 4 5]
5
(5,)


In [ ]:
arr1 = np.arange(6)
print(arr1)

[0 1 2 3 4 5]


In [ ]:
arr_zeros = np.zeros((3,4))
arr_ones = np.ones((3,4))
print(arr_zeros)
print(arr_ones)


print(arr_ones.size)
print(arr_ones.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
12
(3, 4)


In [ ]:
arr3 = np.array([1,2])
arr4 = np.array([1,2])
print(arr3 + arr4)

[2 4]


In [ ]:
arr3 = np.array([1,2])
arr4 = np.array([1,2])
print(arr3 * arr4)


[1 4]


In [ ]:
arr5 = np.array([[1,2],
                 [4,6]])
print(arr5[1])
print(arr5[:,1])


[4 6]
[2 6]


In [ ]:
arr5 = np.array([[1,2],
                 [4,6]])
arr6 = np.array([[3,5],
                [5,6]])
print(arr5 + arr6)


[[ 4  7]
 [ 9 12]]


In [ ]:
arr5 = np.array([[1,2],
                 [4,6]])
arr6 = np.array([[3,5],
                [5,6]])
print(arr5 * arr6)


[[ 3 10]
 [20 36]]


In [ ]:
arr5 = np.array([[1,2],
                 [4,6]])
arr6 = np.array([[3,5],
                [5,6]])
print(arr5 / arr6)


[[0.33333333 0.4       ]
 [0.8        1.        ]]


In [ ]:
arr5 = np.array([[1,2],
                 [4,6]])
arr6 = np.array([[3,5],
                [5,6]])
print(arr5 - arr6)


[[-2 -3]
 [-1  0]]


In [ ]:
a = np.array([1,2,3,4], dtype='int64')
print(a)
print(a.dtype)

[1 2 3 4]
int64


In [ ]:
arr_zeros = np.zeros((3,4))
arr_ones = np.ones((3,4))
print(arr_zeros)
print(arr_ones)


print(arr_ones.size)
print(arr_ones.shape)
print(arr_ones.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
12
(3, 4)
float64


In [10]:
a = np.array([1,2,3,4],dtype='int64')
a.ndim
a.itemsize



8

In [18]:
a = np.array([[1,2],
                 [4,6]])
print(a)
a[0,0]

[[1 2]
 [4 6]]


1

In [20]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [54]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]], dtype='int')
print(a)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)
print(a[1,1:3:1])
print(a[0,1:3:1])



[[1 2 3 4]
 [5 6 7 8]]
int64
8
64
[6 7]
[2 3]


In [59]:
a= np.array([[2,3,4],[5,6,8],[8,10,9]])
print(a)

[[ 2  3  4]
 [ 5  6  8]
 [ 8 10  9]]
